spring.application.name=springbootproject
const API_URL = "http://localhost:PUERTO_CORRECTO/curriculum";
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always-